spring:
  datasource:
    password: root
    username: root
    url: 'jdbc:mysql://localhost:3306/loja?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false'
  jpa:
    hibernate:
      dll-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
